#!/bin/sh

BASEDIR="$HOME/src/typings"
NOTESDIR="$BASEDIR/notes"

while getopts "d:h" c
do
	case $c in
		d)
			if [ ! -d $BASEDIR ]; then
				printf "nn: given base directory '$BASEDIR' not found.\n"
				exit 1
			elif [ ! -d $NOTESDIR ]; then
				printf "nn: given diary directory '$DIARYDIR' not found.\n"
				exit 1
			fi
			if [ $OPTARG = "now" ]; then
				date=$(date +%F)
				file=$NOTESDIR/$date.md
				if [ ! -f $file ]; then
					touch $file
					header_date=$(date '+%d %^b %Y')
					echo '# '$header_date'' > $file
				fi
				$EDITOR $file
			elif [ $OPTARG = "next" ]; then
				date=$(date +%F -d "+1 day")
				file=$NOTESDIR/$date.md
				if [ ! -f $file ]; then
					touch $file
					header_date=$(date -d $date '+%d %^b %Y')
					echo '# '$header_date'' > $file
				fi
				$EDITOR $file
			elif [ $OPTARG = "prev" ]; then
				date=$(date +%F -d "-1 day")
				file=$NOTESDIR/$date.md
				if [ ! -f $file ]; then
					touch $file
					header_date=$(date -d $date '+%d %^b %Y')
					echo '# '$header_date'' > $file
				fi
				$EDITOR $file
			fi
			;;
		h)
			printf "usage: nn [-n] [-d]\n\t-d\tcreate or open today, yesterday or tommorow note\t[now/next/prev]\n"
			;;
	esac
done
